# Generated by Django 4.2.11 on 2024-03-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('level_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameItem',
            fields=[
                ('item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDialouge',
            fields=[
                ('user_dialouge_ID', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('level_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('npc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.npc')),
            ],
        ),
        migrations.CreateModel(
            name='NPCsInLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('npc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.npc')),
            ],
        ),
        migrations.CreateModel(
            name='NPCDialouge',
            fields=[
                ('npc_dialouge_ID', models.AutoField(primary_key=True, serialize=False)),
                ('npc_response', models.TextField()),
                ('level_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('npc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.npc')),
            ],
        ),
    ]
