# Generated by Django 4.2.11 on 2024-03-08 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_npc_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="img",
            field=models.ImageField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="npc",
            name="name",
            field=models.CharField(default="Name of NPC", max_length=100),
        ),
    ]
