# Generated by Django 4.2.11 on 2024-03-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_npc_img_alter_npc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('level_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameItem',
            fields=[
                ('item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='npc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='img',
        ),
        migrations.AddField(
            model_name='npc',
            name='npc_ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='NPCsInLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('npc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.npc')),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('conversation_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('last_conversation', models.TextField()),
                ('npc_response', models.TextField()),
                ('user_input', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('level_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('npc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.npc')),
            ],
        ),
    ]
